[workspace]
members = ["contracts/*"]
resolver = "2"

[workspace.package]
authors = ["The Aha Company"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/stellar-scaffold/cli"
version = "0.0.1"

[workspace.dependencies]
soroban-sdk = "26.1.0"
stellar-access = "0.7.2"
stellar-macros = "0.7.2"
stellar-tokens = "0.7.2"
stellar-registry = "0.0.11"
stellar-xdr = "26.0.1"

[profile.release]
opt-level = "z"
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
overflow-checks = true
strip = true

[profile.release-with-logs]
debug-assertions = true
inherits = "release"
